"""
Educational Q&A posts — five tracks, 10 a day each by default:

  dsa     Daily DSA: a problem, the approach, complexity, Python
  sd      System design: a scenario with numbers, components, trade-offs
  mlsd    ML system design: features, retrieval/ranking, evals, drift
  ai      AI engineering: agent loops/graphs, RAG, tool calling, evals, MCP
  papers  A real, recent paper (Hugging Face daily papers / arXiv) turned
          into "what changed, why it matters, where you'd use it"

Each item is a small JSON record (hook, question, answer, code, visual spec,
tags…). Items are generated by Azure OpenAI the night before (ensure_pool),
rendered to a designed card by `edu_cards`, and posted one per slot by
`post_one`. Three layers keep the posting guarantee intact:

  1. the day's pool (li_edu_pool.json) filled by the morning timers
  2. on-the-fly generation when the pool is empty at post time
  3. the hand-written seed bank (edu_seed.json) when the LLM is unavailable

The answer goes in the post body under LinkedIn's "…more" fold (the
comments API needs partner scopes we don't have) — which also makes people
comment their answer before expanding.
"""

import os
import re
import json
import time
import hashlib
import logging
import datetime
from datetime import timezone, timedelta

log = logging.getLogger("edu")

POOL_BLOB = "li_edu_pool.json"
STATE_BLOB = "li_edu_state.json"
CARDS = "li_edu_cards/"
SEED_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "edu_seed.json")

TRACKS = ["dsa", "sd", "mlsd", "ai", "papers"]
DEFAULT_PER_TRACK = 10
TRACK_NAMES = {"dsa": "DSA", "sd": "System Design", "mlsd": "ML System Design",
               "ai": "AI Engineering", "papers": "Papers"}
TRACK_TAGS = {
    "dsa": "#DSA #DataStructures #Algorithms #CodingInterview #LeetCode #SoftwareEngineering",
    "sd": "#SystemDesign #DistributedSystems #SoftwareArchitecture #TechInterview #Backend",
    "mlsd": "#MachineLearning #MLSystemDesign #MLOps #DataScience #AIEngineering",
    "ai": "#AIEngineering #LLM #Agents #RAG #GenerativeAI #SoftwareEngineering",
    "papers": "#AI #MachineLearning #Research #LLM #DeepLearning #Papers",
}
VISUAL_KINDS = ["array", "code", "boxes", "graph", "tree", "metric", "compare", "table", "none"]

FOLLOW_CTA = ("➕ Follow me for a DSA, system design, ML and AI engineering question every day "
              "— plus every new tech job with the pay range.")

# Companies whose interview loops are known for each track (all have verified
# LinkedIn org URNs in linkedin_autopost.ORG_URNS, so they become blue @tags).
# The generator picks 2-3 per post; these are the allowed sets + rotation order.
COMPANY_POOLS = {
    "dsa":    ["microsoft", "amazon", "google", "meta", "apple", "netflix", "nvidia", "stripe", "databricks", "ibm"],
    "sd":     ["amazon", "google", "microsoft", "netflix", "stripe", "meta", "apple", "databricks", "ibm", "nvidia"],
    "mlsd":   ["meta", "google", "netflix", "amazon", "openai", "microsoft", "nvidia", "databricks", "scaleai", "apple"],
    "ai":     ["openai", "anthropic", "microsoft", "google", "databricks", "scaleai", "cursor", "meta", "amazon", "ramp"],
    "papers": ["openai", "anthropic", "google", "meta", "nvidia", "microsoft", "apple", "amazon", "databricks", "xai"],
}
ROUND_NAME = {"dsa": "DSA rounds", "sd": "system design rounds", "mlsd": "ML system design rounds",
              "ai": "AI engineering interviews", "papers": "research & applied-AI interviews"}
LEVEL_DEFAULT = {
    "dsa":    {"easy": "SDE I / SDE II", "medium": "SDE II / Senior", "hard": "Senior / Staff"},
    "sd":     {"easy": "SDE II / Senior", "medium": "Senior / Staff", "hard": "Staff / Principal / Director"},
    "mlsd":   {"easy": "ML Engineer / Applied Scientist", "medium": "Senior ML Engineer", "hard": "Staff ML / ML Lead"},
    "ai":     {"easy": "AI Engineer / SDE II", "medium": "Senior AI Engineer", "hard": "Staff / Lead AI Engineer"},
    "papers": {"easy": "all levels", "medium": "ML Engineer / Researcher", "hard": "Senior Researcher / Staff"},
}

_BOLD = {}
for _i, _ch in enumerate("ABCDEFGHIJKLMNOPQRSTUVWXYZ"):
    _BOLD[_ch] = chr(0x1D5D4 + _i)              # mathematical sans-serif bold capital
for _i, _ch in enumerate("abcdefghijklmnopqrstuvwxyz"):
    _BOLD[_ch] = chr(0x1D5EE + _i)
for _i, _ch in enumerate("0123456789"):
    _BOLD[_ch] = chr(0x1D7EC + _i)


def bold(text):
    """LinkedIn has no rich text; Unicode sans-serif-bold letters are the
    standard trick for bold in a post. Used only for the hook and section
    headers so the rest stays searchable and readable."""
    return "".join(_BOLD.get(ch, ch) for ch in str(text))

GUIDE = {
    "dsa": ("Pick ONE classic algorithmic problem (two pointers, sliding window, prefix sums, binary search "
            "incl. 'binary search on the answer', BFS/DFS, topological sort, union-find, heaps, tries, "
            "monotonic stack/deque, intervals, dynamic programming, bit tricks, backtracking). State the "
            "problem with a tiny concrete example. The answer must give the key insight, the algorithm in "
            "numbered steps, the complexity, and a correct Python solution of at most 14 lines. "
            "Visual: 'array' (values, highlight, pointers) or 'tree' (level-order values) or 'graph' or "
            "'code' — whichever shows the example best."),
    "sd": ("Pick ONE system design scenario with concrete scale numbers (users, QPS, data size, latency). "
           "The question should be a specific decision, not 'design Twitter'. The answer names the "
           "components, the data flow, the ONE trade-off that matters most, and a back-of-the-envelope "
           "number. Visual: 'boxes' (the data flow, 4-6 items), 'compare' (two options), 'table' or 'metric'."),
    "mlsd": ("Pick ONE ML system design decision: feature stores and training/serving skew, retrieval + "
             "ranking, offline vs online evaluation, A/B and interleaving, drift monitoring, class "
             "imbalance, embeddings and ANN indexes, batch vs real-time inference, model registries and "
             "rollbacks, labeling pipelines. Include concrete numbers. Visual: 'boxes' (pipeline), "
             "'compare', 'table' or 'metric'."),
    "ai": ("Pick ONE AI-engineering topic: agent loops and state graphs (LangGraph-style: nodes, edges, "
           "loops, exit conditions, routers), tool/function calling, structured outputs, RAG chunking and "
           "reranking, hybrid search, evals and LLM-as-judge, guardrails, prompt/KV caching, memory for "
           "agents, MCP servers, multi-agent handoffs, cost/latency budgets, streaming, fallbacks. Give "
           "a concrete production situation. Visual: 'graph' for loops/agents (nodes + edges with a "
           "back-edge), 'boxes' for pipelines, 'compare', 'code' (<= 12 lines) or 'metric'."),
    "papers": ("You are given ONE real paper (title, abstract, url). Write the question as the paper's "
               "central claim posed as a question a curious engineer would ask. The answer: what the "
               "paper changes vs the previous approach, the key result with a number if the abstract has "
               "one, and two concrete use cases. Never invent numbers or results that are not in the "
               "abstract. Visual: 'metric' (a headline number from the abstract), 'compare' (old vs new) "
               "or 'boxes' (the method as a pipeline)."),
}

HOOK_RULES = ("The hook is the first line people see: <= 90 characters, specific to THIS question, "
              "curiosity-driven, no clickbait lies, no 'Google asked this' claims, no emojis. "
              "Use the hook shape you are given for this post and never reuse a hook from the avoid list.")

# Hook shapes rotate per item so ten posts a day never sound alike.
HOOK_SHAPES = [
    "a bold claim that sounds wrong until you read the answer (e.g. 'The fastest solution here never sorts.')",
    "a sharp either/or decision (e.g. 'Push-based feed or pull-based? One of them dies at 10M followers.')",
    "a concrete failure story in one line (e.g. 'The retry looked harmless. It charged the customer twice.')",
    "a number that makes people stop (e.g. '20 tokens per parameter. That one ratio changed how models are trained.')",
    "a direct challenge with a constraint (e.g. 'O(n) time, O(1) space, one pass. Go.')",
    "a 'most engineers get this wrong' framing with the specific mistake named",
    "an interview-room framing without naming any company (e.g. '45 minutes, whiteboard, this question.')",
    "a plain, confident statement of what the reader will be able to do after reading",
]

# Topic banks: one topic is assigned per post, rotating through the bank and
# skipping anything used in the last few days, so a day's ten posts are ten
# different subjects.
TOPICS = {
    "dsa": [
        "two pointers on a sorted array", "sliding window with a variable size", "prefix sums + hash map (subarray sum = K)",
        "binary search on the answer (e.g. minimum capacity / Koko bananas)", "binary search in a rotated sorted array",
        "monotonic stack (next greater element / daily temperatures)", "monotonic deque (sliding window maximum)",
        "fast & slow pointers (cycle detection, middle of list)", "reverse a linked list iteratively and recursively",
        "merge k sorted lists with a heap", "top-k frequent elements (heap vs bucket sort)", "kth largest element (quickselect)",
        "BFS on a grid (shortest path, number of islands)", "DFS with backtracking (subsets / permutations / N-queens)",
        "topological sort (course schedule) and cycle detection in a DAG", "union-find with path compression (connected components)",
        "Dijkstra with a priority queue", "0/1 knapsack and its 1-D space optimisation", "longest increasing subsequence in O(n log n)",
        "edit distance / LCS dynamic programming", "coin change (min coins vs number of ways)", "house robber / max non-adjacent sum",
        "Kadane's maximum subarray and the max product variant", "intervals: merge, insert, minimum meeting rooms",
        "trie: prefix search and word search II", "binary tree traversal without recursion (iterative inorder)",
        "lowest common ancestor in a binary tree and in a BST", "validate a BST (the min/max bound trick)",
        "serialize and deserialize a binary tree", "diameter / max path sum of a binary tree",
        "bit manipulation (single number, counting bits, power of two)", "LRU cache (hash map + doubly linked list)",
        "matrix rotation / spiral order in place", "string: longest palindromic substring (expand around centre)",
        "string: anagram grouping and character counting tricks", "heap-based median of a data stream",
        "two heaps / greedy scheduling (task scheduler)", "greedy with sorting (jump game, gas station)",
        "Floyd's algorithm for the duplicate number", "cyclic sort (first missing positive)",
    ],
    "sd": [
        "URL shortener: ID generation without collisions", "rate limiter: token bucket vs sliding window, distributed with Redis",
        "news feed: fan-out on write vs read, celebrity problem", "idempotency keys for payments and retries",
        "cache-aside vs write-through vs write-behind; cache stampede", "consistent hashing and rebalancing a cache cluster",
        "database sharding: choosing a shard key, hot partitions", "read replicas and replication lag: read-your-writes",
        "message queue vs event log (SQS/RabbitMQ vs Kafka): ordering and replay", "exactly-once processing: what it really means",
        "outbox pattern and change data capture", "saga pattern for distributed transactions", "leader election and distributed locks (fencing tokens)",
        "back-of-the-envelope estimation for a chat app", "WebSockets vs long polling vs SSE for real-time updates",
        "designing a notification system with dedup and rate limits", "search autocomplete (trie + top-k, prefix caching)",
        "designing a distributed unique ID (Snowflake)", "object storage for uploads: presigned URLs, multipart, CDN",
        "designing a job scheduler / delayed queue", "API gateway responsibilities: auth, throttling, routing, retries",
        "circuit breakers, timeouts and retries with jitter", "bloom filters: where they save a database round trip",
        "time-series metrics store: downsampling and retention", "geo search (geohash / quadtree) for nearby drivers",
        "designing a ticket booking system: overselling and locks", "multi-region active-active: conflicts and CRDTs",
        "blue/green vs canary deployments and feature flags", "designing a web crawler: politeness, dedup, frontier",
        "log aggregation pipeline: sampling, indexing, cost", "CAP/PACELC in practice: what a system actually gives up",
        "designing a leaderboard with Redis sorted sets", "designing a key-value store: LSM trees vs B-trees",
        "hot key problem and request coalescing", "designing rate-limited webhooks with retries and signatures",
    ],
    "mlsd": [
        "training/serving skew and feature stores", "two-tower retrieval + ranking for recommendations", "offline metrics vs online A/B; interleaving",
        "data drift vs concept drift monitoring", "class imbalance: metrics and thresholds for fraud", "embedding-based search: ANN indexes (HNSW/IVF) trade-offs",
        "batch vs real-time inference: latency and cost", "model registry, versioning and rollback", "labeling pipelines and active learning",
        "feature engineering for time series without leakage", "point-in-time correct training data", "cold start in recommender systems",
        "position bias and counterfactual evaluation", "shadow deployment and canary for models", "multi-armed bandits for ranking exploration",
        "calibration and why probabilities matter for decisions", "model serving: GPU batching, dynamic batching, autoscaling",
        "retraining cadence and champion/challenger", "guarding against feedback loops in ranking", "privacy: differential privacy and federated learning basics",
        "designing an ML platform: what to standardise first", "evaluation datasets: slices, not averages", "handling delayed labels (conversions arrive days later)",
        "search ranking: learning to rank features and losses", "ads CTR prediction system components", "anomaly detection system for metrics",
        "forecasting system: hierarchical reconciliation", "LLM-based features vs classic features: cost and drift",
        "vector database vs search engine for retrieval", "monitoring embeddings drift",
    ],
    "ai": [
        "agent loop as a state graph with a bounded back-edge (LangGraph style)", "routers and conditional edges in agent graphs",
        "tool calling: schema design and validation retries", "structured outputs: JSON schema mode + validation",
        "RAG chunking strategies and contextual chunk headers", "hybrid search (BM25 + dense) and reranking", "evals: golden sets and LLM-as-judge pitfalls",
        "guardrails: input/output checks, prompt injection defence", "prompt caching vs KV caching: what each saves",
        "agent memory: short-term state vs long-term retrieval", "MCP servers: tools, resources, prompts; when to use MCP over REST",
        "multi-agent handoffs vs a single agent with tools", "streaming responses and partial tool results", "fallback chains across models and providers",
        "cost and latency budgets per request; token accounting", "human-in-the-loop checkpoints in agent graphs", "idempotent tools and side-effect safety for agents",
        "observability for LLM apps: traces, spans, prompt versions", "semantic caching of responses", "context window management: summarisation vs retrieval",
        "reflection / self-critique loops: when they help", "planning: ReAct vs plan-and-execute", "batch inference pipelines with LLMs",
        "fine-tuning vs prompting vs RAG decision", "embedding model selection and dimensionality", "asynchronous tool execution and parallel tool calls",
        "sandboxing code execution for agents", "rate limits and backoff for LLM APIs", "deterministic testing of non-deterministic models",
        "designing a coding agent's edit-verify loop", "long-running agents: checkpoints and resumability",
    ],
}


# ---------- storage helpers ----------

def _load(store, name, default):
    try:
        return json.loads(store.download_blob(name).readall())
    except Exception:
        return default


def _save(store, name, obj):
    store.upload_blob(name, json.dumps(obj), overwrite=True)


def _now():
    return datetime.datetime.now(timezone.utc)


def _cfg(store):
    try:
        import linkedin_client
        return linkedin_client._blob_secrets()
    except Exception:
        return {}


def targets(store, sec=None):
    """{track: posts per day} from li_secrets (edu_dsa, edu_sd, …), 0 if disabled."""
    sec = sec if sec is not None else _cfg(store)
    if str(sec.get("edu_enabled", "true")).lower() != "true":
        return {t: 0 for t in TRACKS}
    out = {}
    for t in TRACKS:
        try:
            out[t] = max(0, min(20, int(sec.get(f"edu_{t}", DEFAULT_PER_TRACK))))
        except Exception:
            out[t] = DEFAULT_PER_TRACK
    return out


# ---------- items ----------

def _slug(s):
    return re.sub(r"[^a-z0-9]+", "-", (s or "").lower()).strip("-")[:60]


def _item_id(track, question):
    return track + "-" + hashlib.sha1(question.encode("utf-8")).hexdigest()[:10]


def validate(item, track):
    """Normalise + sanity-check a generated item. Returns the clean item or None."""
    if not isinstance(item, dict):
        return None
    q = str(item.get("question") or "").strip()
    a = str(item.get("answer") or "").strip()
    hook = str(item.get("hook") or "").strip().strip('"')
    if len(q) < 25 or len(a) < 60 or len(hook) < 10:
        return None
    vis = item.get("visual") if isinstance(item.get("visual"), dict) else {"kind": "none"}
    if vis.get("kind") not in VISUAL_KINDS:
        vis = {"kind": "none"}
    code = str(item.get("code") or "").strip()
    if code and len(code.splitlines()) > 18:
        code = "\n".join(code.splitlines()[:18])
    diff = str(item.get("difficulty") or "").lower()
    diff = diff if diff in ("easy", "medium", "hard") else None
    opts = item.get("options") if isinstance(item.get("options"), list) else []
    opts = [str(o).strip()[:80] for o in opts][:4]
    tags = [re.sub(r"[^A-Za-z0-9]", "", str(t)) for t in (item.get("tags") or []) if str(t).strip()][:3]
    allowed = COMPANY_POOLS.get(track, [])
    companies = []
    for c in (item.get("companies") or []):
        key = re.sub(r"[^a-z]", "", str(c).lower())
        if key in allowed and key not in companies:
            companies.append(key)
    companies = companies[:3]
    level = re.sub(r"\s+", " ", str(item.get("level") or "")).strip(" .")[:48]
    return {"id": _item_id(track, q), "track": track, "hook": hook[:120], "question": q[:420],
            "options": opts, "answer": a[:1400], "code": code, "complexity": str(item.get("complexity") or "")[:120],
            "takeaway": str(item.get("takeaway") or "")[:180], "difficulty": diff, "visual": vis,
            "tags": tags, "url": str(item.get("url") or "")[:300], "source": str(item.get("source") or "")[:80],
            "topic": str(item.get("topic") or "")[:80], "companies": companies, "level": level,
            "created": _now().isoformat()}


def seed_items(track):
    try:
        with open(SEED_FILE, encoding="utf-8") as f:
            bank = json.load(f)
    except Exception:
        return []
    out = []
    for raw in bank.get(track, []):
        it = validate(raw, track)
        if it:
            it["source"] = it["source"] or "seed"
            out.append(it)
    return out


# ---------- generation (LLM) ----------

def _parse_json(text):
    text = (text or "").strip()
    text = re.sub(r"^```(?:json)?\s*|\s*```$", "", text, flags=re.S)
    try:
        return json.loads(text)
    except Exception:
        pass
    m = re.search(r"\{.*\}", text, flags=re.S)
    if m:
        try:
            return json.loads(m.group(0))
        except Exception:
            return None
    return None


def _llm(store, sec, messages, max_tokens=1400):
    ep, key = sec.get("aoai_endpoint") or os.getenv("AOAI_ENDPOINT"), sec.get("aoai_key") or os.getenv("AOAI_KEY")
    if not (ep and key):
        raise RuntimeError("AOAI not configured")
    import llm_chat
    return llm_chat.chat(ep, key, sec.get("aoai_deployment") or os.getenv("AOAI_DEPLOYMENT", "gpt-4o-mini"),
                         messages, max_tokens=max_tokens)


def _recent_titles(state, track, n=40):
    return [u["q"] for u in state.get("used", []) if u.get("track") == track][-n:]


def _paper_candidates(store, state):
    """Recent real papers not yet used: [{title, url, snippet, source}]."""
    seen = set(state.get("papers_seen", []))
    out = []
    try:
        import filler
        for p in filler.fetch_papers(limit=20):
            if p["url"] not in seen:
                out.append(p)
    except Exception as e:
        log.info("hf papers failed: %s", e)
    if len(out) < 5:
        try:
            import requests
            import filler
            r = requests.get("http://export.arxiv.org/api/query?search_query=cat:cs.AI+OR+cat:cs.LG+OR+cat:cs.CL"
                             "&sortBy=submittedDate&sortOrder=descending&max_results=30", timeout=15)
            for x in filler.parse_feed(r.content):
                url = x["url"].replace("http://", "https://")
                if url not in seen:
                    out.append({"title": x["title"], "url": url, "snippet": x["snippet"], "source": "arXiv"})
        except Exception as e:
            log.info("arxiv failed: %s", e)
    return out


def pick_topic(track, state, pool_items=()):
    """Next topic from the bank: skip topics used in the last 30 posts of the
    track and anything already in today's pool; rotate by counter."""
    bank = TOPICS.get(track) or []
    if not bank:
        return None
    recent = {u.get("topic") for u in state.get("used", []) if u.get("track") == track}
    recent |= {it.get("topic") for it in pool_items}
    start = int((state.get("counters") or {}).get(track, 0))
    for k in range(len(bank)):
        t = bank[(start + k) % len(bank)]
        if t not in recent:
            return t
    return bank[start % len(bank)]


def pick_shape(state, track):
    n = int((state.get("counters") or {}).get(track, 0))
    return HOOK_SHAPES[n % len(HOOK_SHAPES)]


def generate_one(store, track, sec=None, state=None, paper=None, topic=None, shape=None, avoid=()):
    """One LLM call → validated item (or None). Raises only if AOAI is not configured."""
    sec = sec if sec is not None else _cfg(store)
    state = state if state is not None else _load(store, STATE_BLOB, {"used": [], "papers_seen": []})
    style = str(sec.get("style_notes") or "").strip()
    recent = (_recent_titles(state, track) + [a for a in avoid if a])[-60:]
    topic = topic or (pick_topic(track, state) if track != "papers" else None)
    shape = shape or pick_shape(state, track)
    system = (
        "You write one LinkedIn post for software engineers: a question and its answer in the track "
        f"'{TRACK_NAMES[track]}'. Audience: engineers preparing for interviews and building real systems. "
        "Be correct, concrete and specific; no fluff, no marketing. " + HOOK_RULES + "\n\n"
        "Track guidance: " + GUIDE[track] + "\n\n"
        "Return ONLY a JSON object with these keys:\n"
        "hook (string <= 90 chars), question (string, self-contained, <= 400 chars), "
        "options (array of 0-4 short strings, only when a multiple-choice framing makes people comment), "
        "difficulty ('easy'|'medium'|'hard'), "
        "answer (string, <= 550 chars: first line 'Key idea: ...', then at most 3 numbered steps, each one "
        "line; no code inside answer), code (string, Python, <= 10 lines, or empty), "
        "complexity (string, e.g. 'Time O(n) · Space O(1)', or a key number for design topics), "
        "takeaway (one sentence), tags (2-3 CamelCase hashtags without #), "
        f"companies (array of 2-3 keys from {json.dumps(COMPANY_POOLS[track])} whose interview loops are known "
        "to ask this kind of question; be truthful — pick companies where this topic is commonly reported), "
        "level (string, the roles/levels this is typically asked for, e.g. 'SDE II / Senior' or "
        "'Staff / Principal' or 'all levels'), "
        "visual (object: one of " + json.dumps(VISUAL_KINDS) + " — schemas: "
        "{kind:'array', values:[numbers or short strings], highlight:[indices], pointers:{index:'label'}, caption:''} | "
        "{kind:'code', lang:'python', code:'<= 12 short lines'} | {kind:'boxes', items:['4-6 labels']} | "
        "{kind:'graph', nodes:['3-6 labels'], edges:[[from,to],...]} | {kind:'tree', values:[level-order, null for gaps]} | "
        "{kind:'metric', big:'headline number', small:'what it is', big2:'', small2:''} | "
        "{kind:'compare', left:{title:'', points:['<=4']}, right:{title:'', points:['<=4']}} | "
        "{kind:'table', header:['','A','B'], rows:[['row','x','y']]} | {kind:'none'}).\n"
        "The visual must illustrate THIS question (the example array, the flow, the loop, the number).\n"
        + f"Hook shape for this post: {shape}\n"
        + (f"AVOID — do not reuse these hooks/questions or their framing: {json.dumps(recent)}\n" if recent else "")
        + (f"Owner's style notes (follow them): {style}\n" if style else "")
        + "No markdown, no code fences, JSON only.")
    if track == "papers":
        if not paper:
            return None
        user = (f"Paper title: {paper['title']}\nURL: {paper['url']}\nSource: {paper.get('source', '')}\n"
                f"Abstract: {(paper.get('snippet') or '')[:1500]}\n\nWrite the post JSON. Set url to the paper URL.")
    else:
        seed = hashlib.sha1(f"{track}{topic}{_now().isoformat()}".encode()).hexdigest()[:6]
        user = (f"Topic for this post: {topic}.\nDifficulty: {['easy', 'medium', 'medium', 'hard'][int(seed, 16) % 4]}.\n"
                f"Write the post JSON now (variation seed {seed}).")
    out = _llm(store, sec, [{"role": "system", "content": system}, {"role": "user", "content": user}])
    item = validate(_parse_json(out), track)
    if item and track == "papers":
        item["url"] = paper["url"]
        item["source"] = paper.get("source") or "paper"
        item["topic"] = paper["title"][:80]
    elif item:
        item["source"] = "llm"
        item["topic"] = topic
    return item


# ---------- pool ----------

def pool(store):
    p = _load(store, POOL_BLOB, {})
    return {t: list(p.get(t, [])) for t in TRACKS}


def _logo_loader():
    try:
        import jobs
        return jobs.logo_loader
    except Exception:
        return None


def _render_and_store(store, item):
    import edu_cards
    number = item.get("number")
    png = edu_cards.render(item["track"], item["question"], item.get("visual"), number, item.get("difficulty"),
                           companies=companies_for(item, number), logo_loader=_logo_loader())
    blob = CARDS + item["id"] + ".png"
    store.upload_blob(blob, png, overwrite=True)
    item["card_blob"] = blob
    return item


def _next_number(state, track):
    state.setdefault("counters", {})
    state["counters"][track] = int(state["counters"].get(track, 0)) + 1
    return state["counters"][track]


def ensure_pool(store, track, n=None, budget_s=420):
    """Top the track's pool up to n items (default = today's target). Uses the
    LLM; falls back to unused seed items. Time-boxed for serverless hosts."""
    t0 = time.time()
    sec = _cfg(store)
    n = n if n is not None else targets(store, sec)[track]
    p = pool(store)
    state = _load(store, STATE_BLOB, {"used": [], "papers_seen": []})
    have = {it["id"] for it in p[track]}
    used = {u.get("id") for u in state.get("used", [])}
    notes = []
    papers = _paper_candidates(store, state) if track == "papers" else []
    llm_ok = True
    added = 0
    while len(p[track]) < n and time.time() - t0 < budget_s:
        item = None
        if llm_ok:
            try:
                paper = papers.pop(0) if track == "papers" and papers else None
                if track == "papers" and not paper:
                    llm_ok = False              # no unseen papers left → seeds
                else:
                    avoid = [it["hook"] for it in p[track]] + [it["question"][:90] for it in p[track]]
                    topic = pick_topic(track, state, p[track]) if track != "papers" else None
                    item = generate_one(store, track, sec, state, paper, topic=topic, avoid=avoid)
                    if paper:
                        state.setdefault("papers_seen", []).append(paper["url"])
                    if item and any(item["hook"].lower()[:40] == it["hook"].lower()[:40] for it in p[track]):
                        item = None             # near-duplicate hook → try again
            except Exception as e:
                notes.append(f"{track}: llm unavailable ({str(e)[:80]})")
                llm_ok = False
        if item is None and not llm_ok:
            fresh = [s for s in seed_items(track) if s["id"] not in have and s["id"] not in used]
            if not fresh:
                break
            item = fresh[0]
        if item is None:
            continue
        if item["id"] in have or item["id"] in used:
            continue
        item["number"] = _next_number(state, track)
        try:
            _render_and_store(store, item)
        except Exception as e:
            log.warning("render failed for %s: %s", item["id"], e)
            item["card_blob"] = ""
        p[track].append(item)
        have.add(item["id"])
        added += 1
        # persist as we go so a timeout never loses work
        allp = _load(store, POOL_BLOB, {})
        allp[track] = p[track]
        _save(store, POOL_BLOB, allp)
        _save(store, STATE_BLOB, state)
    notes.append(f"{track}: pool {len(p[track])}/{n} (+{added}, {time.time() - t0:.0f}s)")
    return notes


def ensure_all(store, budget_s=540):
    notes = []
    t0 = time.time()
    for t in TRACKS:
        left = budget_s - (time.time() - t0)
        if left < 20:
            notes.append("budget exhausted")
            break
        notes += ensure_pool(store, t, budget_s=min(left, 200))
    return notes


def reset_pool(store, tracks=None):
    """Drop prepared items (all tracks, or the given ones) so they regenerate."""
    if tracks is None:
        _save(store, POOL_BLOB, {})
        return ["edu pool cleared — regenerating on the next timer / on demand"]
    allp = _load(store, POOL_BLOB, {})
    for t in tracks:
        allp[t] = []
    _save(store, POOL_BLOB, allp)
    return [f"edu pool cleared for {', '.join(tracks)}"]


def regenerate(store, tracks=None, budget_s=540):
    """Reset + refill in one call (HTTP/ops action)."""
    tracks = tracks or [t for t in TRACKS if t != "papers"]
    notes = reset_pool(store, tracks)
    t0 = time.time()
    for t in tracks:
        left = budget_s - (time.time() - t0)
        if left < 20:
            notes.append("budget exhausted")
            break
        notes += ensure_pool(store, t, budget_s=min(left, 200))
    return notes


# ---------- caption ----------

def companies_for(item, number=None):
    """The 2-3 companies to name: the generator's pick, else a rotation over the
    track's pool (so the same three aren't tagged all day)."""
    got = [c for c in (item.get("companies") or []) if c in COMPANY_POOLS.get(item["track"], [])]
    if len(got) >= 2:
        return got[:3]
    pool = COMPANY_POOLS.get(item["track"], [])
    n = int(number or item.get("number") or 0)
    extra = [pool[(n * 3 + k) % len(pool)] for k in range(3)] if pool else []
    return (got + [c for c in extra if c not in got])[:3]


def level_for(item):
    return item.get("level") or LEVEL_DEFAULT[item["track"]].get(item.get("difficulty") or "medium", "all levels")


def _short_answer(answer, limit=600):
    """Key idea + up to 3 steps; the hook does the selling, the answer stays tight."""
    lines = [l.rstrip() for l in (answer or "").splitlines() if l.strip()]
    out, steps = [], 0
    for l in lines:
        if re.match(r"^\s*\d+[.)]", l):
            steps += 1
            if steps > 3:
                continue
        out.append(l)
    txt = "\n".join(out)
    if len(txt) > limit:
        txt = txt[:limit].rsplit(" ", 1)[0].rstrip(" ,;:") + "\u2026"
    return txt


def caption_parts(item, include_code=False):
    """Returns (text, mentions) — mentions are (display_name, org_urn) for the
    companies named in the 'Asked at' line, so they become blue @tags."""
    import card_builder, linkedin_autopost as la
    t = item["track"]
    comps = companies_for(item)
    names = [card_builder.display_name(c) for c in comps]
    mentions = [(card_builder.display_name(c), la.ORG_URNS[c]) for c in comps if la.ORG_URNS.get(c)]
    if len(names) >= 2:
        asked = f"\U0001F3E2 Asked in {ROUND_NAME[t]} at companies like " + ", ".join(names[:-1]) + f" and {names[-1]}"
    elif names:
        asked = f"\U0001F3E2 Asked in {ROUND_NAME[t]} at companies like {names[0]}"
    else:
        asked = ""
    body = _short_answer(item["answer"])
    if body.lower().startswith("key idea:"):
        body = bold("Key idea:") + body[len("key idea:"):]
    lines = [bold(item["hook"]), "", f"\U0001F9E9 {item['question']}"]
    if item.get("options"):
        lines += [""] + [f"  {o}" for o in item["options"]]
    lines.append("")
    if asked:
        lines.append(asked)
    lines.append(f"\U0001F3AF {bold('Level:')} {level_for(item)}")
    lines += ["", "\U0001F4AC Comment your approach before you expand \U0001F447", "",
              "\u2501\u2501\u2501 " + bold("Answer") + " \u2501\u2501\u2501", body]
    if include_code and item.get("code"):
        lines += ["", "\U0001F40D " + bold("Code"), item["code"]]
    if item.get("complexity"):
        lines += ["", f"\u23F1 {item['complexity']}"]
    if item.get("takeaway"):
        lines += ["", f"\U0001F511 {bold('Takeaway:')} {item['takeaway']}"]
    if t == "papers" and item.get("url"):
        lines += ["", f"\U0001F4C4 Paper: {item['url']}"]
    lines += ["", FOLLOW_CTA, "\u267B\ufe0f Repost to help someone prepping this week.", "",
              TRACK_TAGS[t] + "".join(f" #{x}" for x in item.get("tags", []) if x)
              + "".join(f" #{n.replace(' ', '')}" for n in names)]
    cap = "\n".join(lines)
    if len(cap) > 2900:
        cap = cap[:2860].rsplit("\n", 1)[0] + "\n\n" + TRACK_TAGS[t]
    return cap, mentions


def caption(item, include_code=False):
    return caption_parts(item, include_code)[0]


# ---------- posting ----------

def post_one(store, track):
    """Post the next item for `track`: pool → generate on the fly → seed bank.
    Returns notes; '1 posted, …' on success (never raises)."""
    import linkedin_client
    p = pool(store)
    state = _load(store, STATE_BLOB, {"used": [], "papers_seen": []})
    item = None
    src = "pool"
    if p[track]:
        item = p[track].pop(0)
        allp = _load(store, POOL_BLOB, {})
        allp[track] = p[track]
        _save(store, POOL_BLOB, allp)
    else:
        src = "on-the-fly"
        try:
            sec = _cfg(store)
            paper = None
            if track == "papers":
                cands = _paper_candidates(store, state)
                paper = cands[0] if cands else None
                if paper:
                    state.setdefault("papers_seen", []).append(paper["url"])
            item = generate_one(store, track, sec, state, paper,
                                topic=pick_topic(track, state) if track != "papers" else None) if (track != "papers" or paper) else None
        except Exception as e:
            log.info("on-the-fly generation failed: %s", e)
            item = None
        if item is None:
            src = "seed"
            used = {u.get("id") for u in state.get("used", [])}
            fresh = [s for s in seed_items(track) if s["id"] not in used]
            if not fresh:
                return [f"edu {track}: nothing available (pool empty, LLM down, seeds used)"]
            item = fresh[0]
        item["number"] = _next_number(state, track)
        try:
            _render_and_store(store, item)
        except Exception as e:
            log.warning("render failed: %s", e)
            item["card_blob"] = ""
    png = None
    if item.get("card_blob"):
        try:
            png = store.download_blob(item["card_blob"]).readall()
        except Exception:
            png = None
    if png is None:
        try:
            import edu_cards
            png = edu_cards.render(track, item["question"], item.get("visual"), item.get("number"), item.get("difficulty"),
                                   companies=companies_for(item), logo_loader=_logo_loader())
        except Exception:
            png = None
    include_code = str(_cfg(store).get("edu_code", "false")).lower() == "true"
    text, mentions = caption_parts(item, include_code)
    title = f"{TRACK_NAMES[track]}: {item['hook'][:80]}"
    note = ""
    try:
        if png:
            urn = linkedin_client.post_with_image(text, png, title=title, mentions=mentions)
        else:
            urn = linkedin_client.post_text(text, mentions=mentions)
    except Exception as e:
        try:
            urn = linkedin_client.post_text(text, mentions=mentions)
            note = f" (text-only after: {str(e)[:80]})"
        except Exception as e2:
            # put it back so the content isn't lost
            if src == "pool":
                allp = _load(store, POOL_BLOB, {})
                allp[track] = [item] + list(allp.get(track, []))
                _save(store, POOL_BLOB, allp)
            return [f"edu {track} failed: {str(e)[:100]} | text: {str(e2)[:80]}"]
    state.setdefault("used", []).append({"id": item["id"], "track": track, "q": item["question"][:90],
                                         "topic": item.get("topic"), "ts": _now().isoformat(), "urn": urn})
    state["used"] = state["used"][-600:]
    _save(store, STATE_BLOB, state)
    try:
        plog = _load(store, "li_post_log.json", [])
        plog.append({"ts": _now().isoformat(), "company": "edu", "variant": track, "urn": urn,
                     "title": item["hook"][:120], "source": src})
        _save(store, "li_post_log.json", plog[-2000:])
    except Exception:
        pass
    return [f"posted edu {track} #{item.get('number')} ({src}): {item['hook'][:60]} {urn}{note}",
            f"1 posted, {len(pool(store)[track])} {track} left"]


# ---------- digests for the daily email ----------

def plan_text(store):
    """Today's queued questions per track (for the morning email)."""
    p = pool(store)
    tg = targets(store)
    lines = []
    for t in TRACKS:
        items = p[t]
        lines.append(f"{TRACK_NAMES[t]} ({len(items)} ready of {tg[t]} planned):")
        for it in items[:tg[t]]:
            lines.append(f"  • {it['hook']}")
        if not items:
            lines.append("  (generated on the fly at post time)")
    return "\n".join(lines)


def posted_text(store, hours=24):
    """What went out in the last `hours`, grouped, with links."""
    plog = _load(store, "li_post_log.json", [])
    cutoff = (_now() - timedelta(hours=hours)).isoformat()
    recent = [p for p in plog if p.get("ts", "") >= cutoff]
    by = {}
    for p in recent:
        by.setdefault(p.get("variant"), []).append(p)
    jobs = sum(len(v) for k, v in by.items() if k and k.endswith("_hook"))
    lines = [f"Posted in the last {hours}h: {len(recent)} total — {jobs} job cards, "
             + ", ".join(f"{len(by.get(t, []))} {TRACK_NAMES[t]}" for t in TRACKS)
             + f", {len(by.get('poll', []))} poll, {len(by.get('carousel', []))} carousels, "
             f"{sum(len(by.get(k, [])) for k in ('news', 'hn', 'paper', 'chart'))} news/charts"]
    for t in TRACKS:
        for p in by.get(t, [])[:10]:
            urn = p.get("urn") or ""
            link = f"https://www.linkedin.com/feed/update/{urn}/" if urn.startswith("urn:") else ""
            lines.append(f"  [{TRACK_NAMES[t]}] {p.get('title', '')[:70]}  {link}")
    return "\n".join(lines)
