"""
Educational Q&A posts — five tracks, 10 a day each by default:

  dsa     Daily DSA: a problem, the approach, complexity, Python
  sd      System design: a scenario with numbers, components, trade-offs
  mlsd    ML system design: features, retrieval/ranking, evals, drift
  ai      AI engineering: agent loops/graphs, RAG, tool calling, evals, MCP
  papers  A real, recent paper (Hugging Face daily papers / arXiv) turned
          into "what changed, why it matters, where you'd use it"

Each item is a small JSON record (hook, question, answer, code, visual spec,
tags…). Items are generated by Azure OpenAI the night before (ensure_pool),
rendered to a designed card by `edu_cards`, and posted one per slot by
`post_one`. Three layers keep the posting guarantee intact:

  1. the day's pool (li_edu_pool.json) filled by the morning timers
  2. on-the-fly generation when the pool is empty at post time
  3. the hand-written seed bank (edu_seed.json) when the LLM is unavailable

The answer goes in the post body under LinkedIn's "…more" fold (the
comments API needs partner scopes we don't have) — which also makes people
comment their answer before expanding.
"""

import os
import re
import json
import time
import hashlib
import logging
import datetime
from datetime import timezone, timedelta

log = logging.getLogger("edu")

POOL_BLOB = "li_edu_pool.json"
STATE_BLOB = "li_edu_state.json"
CARDS = "li_edu_cards/"
SEED_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "edu_seed.json")

TRACKS = ["dsa", "sd", "mlsd", "ai", "papers"]
DEFAULT_PER_TRACK = 10
TRACK_NAMES = {"dsa": "DSA", "sd": "System Design", "mlsd": "ML System Design",
               "ai": "AI Engineering", "papers": "Papers"}
TRACK_TAGS = {
    "dsa": "#DSA #DataStructures #Algorithms #CodingInterview #LeetCode #SoftwareEngineering",
    "sd": "#SystemDesign #DistributedSystems #SoftwareArchitecture #TechInterview #Backend",
    "mlsd": "#MachineLearning #MLSystemDesign #MLOps #DataScience #AIEngineering",
    "ai": "#AIEngineering #LLM #Agents #RAG #GenerativeAI #SoftwareEngineering",
    "papers": "#AI #MachineLearning #Research #LLM #DeepLearning #Papers",
}
VISUAL_KINDS = ["array", "code", "boxes", "graph", "tree", "metric", "compare", "table", "none"]

FOLLOW_CTA = ("➕ Follow me for a DSA, system design, ML and AI engineering question every day "
              "— plus every new tech job with the pay range.")

GUIDE = {
    "dsa": ("Pick ONE classic algorithmic problem (two pointers, sliding window, prefix sums, binary search "
            "incl. 'binary search on the answer', BFS/DFS, topological sort, union-find, heaps, tries, "
            "monotonic stack/deque, intervals, dynamic programming, bit tricks, backtracking). State the "
            "problem with a tiny concrete example. The answer must give the key insight, the algorithm in "
            "numbered steps, the complexity, and a correct Python solution of at most 14 lines. "
            "Visual: 'array' (values, highlight, pointers) or 'tree' (level-order values) or 'graph' or "
            "'code' — whichever shows the example best."),
    "sd": ("Pick ONE system design scenario with concrete scale numbers (users, QPS, data size, latency). "
           "The question should be a specific decision, not 'design Twitter'. The answer names the "
           "components, the data flow, the ONE trade-off that matters most, and a back-of-the-envelope "
           "number. Visual: 'boxes' (the data flow, 4-6 items), 'compare' (two options), 'table' or 'metric'."),
    "mlsd": ("Pick ONE ML system design decision: feature stores and training/serving skew, retrieval + "
             "ranking, offline vs online evaluation, A/B and interleaving, drift monitoring, class "
             "imbalance, embeddings and ANN indexes, batch vs real-time inference, model registries and "
             "rollbacks, labeling pipelines. Include concrete numbers. Visual: 'boxes' (pipeline), "
             "'compare', 'table' or 'metric'."),
    "ai": ("Pick ONE AI-engineering topic: agent loops and state graphs (LangGraph-style: nodes, edges, "
           "loops, exit conditions, routers), tool/function calling, structured outputs, RAG chunking and "
           "reranking, hybrid search, evals and LLM-as-judge, guardrails, prompt/KV caching, memory for "
           "agents, MCP servers, multi-agent handoffs, cost/latency budgets, streaming, fallbacks. Give "
           "a concrete production situation. Visual: 'graph' for loops/agents (nodes + edges with a "
           "back-edge), 'boxes' for pipelines, 'compare', 'code' (<= 12 lines) or 'metric'."),
    "papers": ("You are given ONE real paper (title, abstract, url). Write the question as the paper's "
               "central claim posed as a question a curious engineer would ask. The answer: what the "
               "paper changes vs the previous approach, the key result with a number if the abstract has "
               "one, and two concrete use cases. Never invent numbers or results that are not in the "
               "abstract. Visual: 'metric' (a headline number from the abstract), 'compare' (old vs new) "
               "or 'boxes' (the method as a pipeline)."),
}

HOOK_RULES = ("The hook is the first line people see: <= 90 characters, specific, curiosity-driven, no "
              "clickbait lies, no 'Google asked this' claims, no emojis. Good shapes: a surprising "
              "consequence ('Your model was 94% accurate offline and useless in prod'), a sharp "
              "either/or ('Token bucket or sliding window?'), a challenge ('Can you do it in O(n)?').")


# ---------- storage helpers ----------

def _load(store, name, default):
    try:
        return json.loads(store.download_blob(name).readall())
    except Exception:
        return default


def _save(store, name, obj):
    store.upload_blob(name, json.dumps(obj), overwrite=True)


def _now():
    return datetime.datetime.now(timezone.utc)


def _cfg(store):
    try:
        import linkedin_client
        return linkedin_client._blob_secrets()
    except Exception:
        return {}


def targets(store, sec=None):
    """{track: posts per day} from li_secrets (edu_dsa, edu_sd, …), 0 if disabled."""
    sec = sec if sec is not None else _cfg(store)
    if str(sec.get("edu_enabled", "true")).lower() != "true":
        return {t: 0 for t in TRACKS}
    out = {}
    for t in TRACKS:
        try:
            out[t] = max(0, min(20, int(sec.get(f"edu_{t}", DEFAULT_PER_TRACK))))
        except Exception:
            out[t] = DEFAULT_PER_TRACK
    return out


# ---------- items ----------

def _slug(s):
    return re.sub(r"[^a-z0-9]+", "-", (s or "").lower()).strip("-")[:60]


def _item_id(track, question):
    return track + "-" + hashlib.sha1(question.encode("utf-8")).hexdigest()[:10]


def validate(item, track):
    """Normalise + sanity-check a generated item. Returns the clean item or None."""
    if not isinstance(item, dict):
        return None
    q = str(item.get("question") or "").strip()
    a = str(item.get("answer") or "").strip()
    hook = str(item.get("hook") or "").strip().strip('"')
    if len(q) < 25 or len(a) < 60 or len(hook) < 10:
        return None
    vis = item.get("visual") if isinstance(item.get("visual"), dict) else {"kind": "none"}
    if vis.get("kind") not in VISUAL_KINDS:
        vis = {"kind": "none"}
    code = str(item.get("code") or "").strip()
    if code and len(code.splitlines()) > 18:
        code = "\n".join(code.splitlines()[:18])
    diff = str(item.get("difficulty") or "").lower()
    diff = diff if diff in ("easy", "medium", "hard") else None
    opts = item.get("options") if isinstance(item.get("options"), list) else []
    opts = [str(o).strip()[:80] for o in opts][:4]
    tags = [re.sub(r"[^A-Za-z0-9]", "", str(t)) for t in (item.get("tags") or []) if str(t).strip()][:3]
    return {"id": _item_id(track, q), "track": track, "hook": hook[:120], "question": q[:420],
            "options": opts, "answer": a[:1400], "code": code, "complexity": str(item.get("complexity") or "")[:120],
            "takeaway": str(item.get("takeaway") or "")[:180], "difficulty": diff, "visual": vis,
            "tags": tags, "url": str(item.get("url") or "")[:300], "source": str(item.get("source") or "")[:80],
            "created": _now().isoformat()}


def seed_items(track):
    try:
        with open(SEED_FILE, encoding="utf-8") as f:
            bank = json.load(f)
    except Exception:
        return []
    out = []
    for raw in bank.get(track, []):
        it = validate(raw, track)
        if it:
            it["source"] = it["source"] or "seed"
            out.append(it)
    return out


# ---------- generation (LLM) ----------

def _parse_json(text):
    text = (text or "").strip()
    text = re.sub(r"^```(?:json)?\s*|\s*```$", "", text, flags=re.S)
    try:
        return json.loads(text)
    except Exception:
        pass
    m = re.search(r"\{.*\}", text, flags=re.S)
    if m:
        try:
            return json.loads(m.group(0))
        except Exception:
            return None
    return None


def _llm(store, sec, messages, max_tokens=1400):
    ep, key = sec.get("aoai_endpoint") or os.getenv("AOAI_ENDPOINT"), sec.get("aoai_key") or os.getenv("AOAI_KEY")
    if not (ep and key):
        raise RuntimeError("AOAI not configured")
    import llm_chat
    return llm_chat.chat(ep, key, sec.get("aoai_deployment") or os.getenv("AOAI_DEPLOYMENT", "gpt-4o-mini"),
                         messages, max_tokens=max_tokens)


def _recent_titles(state, track, n=40):
    return [u["q"] for u in state.get("used", []) if u.get("track") == track][-n:]


def _paper_candidates(store, state):
    """Recent real papers not yet used: [{title, url, snippet, source}]."""
    seen = set(state.get("papers_seen", []))
    out = []
    try:
        import filler
        for p in filler.fetch_papers(limit=20):
            if p["url"] not in seen:
                out.append(p)
    except Exception as e:
        log.info("hf papers failed: %s", e)
    if len(out) < 5:
        try:
            import requests
            import filler
            r = requests.get("http://export.arxiv.org/api/query?search_query=cat:cs.AI+OR+cat:cs.LG+OR+cat:cs.CL"
                             "&sortBy=submittedDate&sortOrder=descending&max_results=30", timeout=15)
            for x in filler.parse_feed(r.content):
                url = x["url"].replace("http://", "https://")
                if url not in seen:
                    out.append({"title": x["title"], "url": url, "snippet": x["snippet"], "source": "arXiv"})
        except Exception as e:
            log.info("arxiv failed: %s", e)
    return out


def generate_one(store, track, sec=None, state=None, paper=None):
    """One LLM call → validated item (or None). Raises only if AOAI is not configured."""
    sec = sec if sec is not None else _cfg(store)
    state = state if state is not None else _load(store, STATE_BLOB, {"used": [], "papers_seen": []})
    style = str(sec.get("style_notes") or "").strip()
    recent = _recent_titles(state, track)
    system = (
        "You write one LinkedIn post for software engineers: a question and its answer in the track "
        f"'{TRACK_NAMES[track]}'. Audience: engineers preparing for interviews and building real systems. "
        "Be correct, concrete and specific; no fluff, no marketing. " + HOOK_RULES + "\n\n"
        "Track guidance: " + GUIDE[track] + "\n\n"
        "Return ONLY a JSON object with these keys:\n"
        "hook (string <= 90 chars), question (string, self-contained, <= 400 chars), "
        "options (array of 0-4 short strings, only when a multiple-choice framing makes people comment), "
        "difficulty ('easy'|'medium'|'hard'), answer (string, <= 1200 chars, plain text with numbered steps "
        "or short paragraphs, newlines allowed), code (string, Python, <= 14 lines, or empty), "
        "complexity (string, e.g. 'Time O(n) · Space O(1)', or a key number for design topics), "
        "takeaway (one sentence), tags (2-3 CamelCase hashtags without #), "
        "visual (object: one of " + json.dumps(VISUAL_KINDS) + " — schemas: "
        "{kind:'array', values:[numbers or short strings], highlight:[indices], pointers:{index:'label'}, caption:''} | "
        "{kind:'code', lang:'python', code:'<= 12 short lines'} | {kind:'boxes', items:['4-6 labels']} | "
        "{kind:'graph', nodes:['3-6 labels'], edges:[[from,to],...]} | {kind:'tree', values:[level-order, null for gaps]} | "
        "{kind:'metric', big:'headline number', small:'what it is', big2:'', small2:''} | "
        "{kind:'compare', left:{title:'', points:['<=4']}, right:{title:'', points:['<=4']}} | "
        "{kind:'table', header:['','A','B'], rows:[['row','x','y']]} | {kind:'none'}).\n"
        "The visual must illustrate THIS question (the example array, the flow, the loop, the number).\n"
        + (f"Do not repeat these recent topics: {json.dumps(recent)}\n" if recent else "")
        + (f"Owner's style notes (follow them): {style}\n" if style else "")
        + "No markdown, no code fences, JSON only.")
    if track == "papers":
        if not paper:
            return None
        user = (f"Paper title: {paper['title']}\nURL: {paper['url']}\nSource: {paper.get('source', '')}\n"
                f"Abstract: {(paper.get('snippet') or '')[:1500]}\n\nWrite the post JSON. Set url to the paper URL.")
    else:
        seed = hashlib.sha1(f"{track}{_now().isoformat()}".encode()).hexdigest()[:6]
        user = f"Write the post JSON now. Variation seed: {seed}. Difficulty for this one: {['easy', 'medium', 'medium', 'hard'][int(seed, 16) % 4]}."
    out = _llm(store, sec, [{"role": "system", "content": system}, {"role": "user", "content": user}])
    item = validate(_parse_json(out), track)
    if item and track == "papers":
        item["url"] = paper["url"]
        item["source"] = paper.get("source") or "paper"
    elif item:
        item["source"] = "llm"
    return item


# ---------- pool ----------

def pool(store):
    p = _load(store, POOL_BLOB, {})
    return {t: list(p.get(t, [])) for t in TRACKS}


def _render_and_store(store, item):
    import edu_cards
    number = item.get("number")
    png = edu_cards.render(item["track"], item["question"], item.get("visual"), number, item.get("difficulty"))
    blob = CARDS + item["id"] + ".png"
    store.upload_blob(blob, png, overwrite=True)
    item["card_blob"] = blob
    return item


def _next_number(state, track):
    state.setdefault("counters", {})
    state["counters"][track] = int(state["counters"].get(track, 0)) + 1
    return state["counters"][track]


def ensure_pool(store, track, n=None, budget_s=420):
    """Top the track's pool up to n items (default = today's target). Uses the
    LLM; falls back to unused seed items. Time-boxed for serverless hosts."""
    t0 = time.time()
    sec = _cfg(store)
    n = n if n is not None else targets(store, sec)[track]
    p = pool(store)
    state = _load(store, STATE_BLOB, {"used": [], "papers_seen": []})
    have = {it["id"] for it in p[track]}
    used = {u.get("id") for u in state.get("used", [])}
    notes = []
    papers = _paper_candidates(store, state) if track == "papers" else []
    llm_ok = True
    added = 0
    while len(p[track]) < n and time.time() - t0 < budget_s:
        item = None
        if llm_ok:
            try:
                paper = papers.pop(0) if track == "papers" and papers else None
                if track == "papers" and not paper:
                    llm_ok = False              # no unseen papers left → seeds
                else:
                    item = generate_one(store, track, sec, state, paper)
                    if paper:
                        state.setdefault("papers_seen", []).append(paper["url"])
            except Exception as e:
                notes.append(f"{track}: llm unavailable ({str(e)[:80]})")
                llm_ok = False
        if item is None and not llm_ok:
            fresh = [s for s in seed_items(track) if s["id"] not in have and s["id"] not in used]
            if not fresh:
                break
            item = fresh[0]
        if item is None:
            continue
        if item["id"] in have or item["id"] in used:
            continue
        item["number"] = _next_number(state, track)
        try:
            _render_and_store(store, item)
        except Exception as e:
            log.warning("render failed for %s: %s", item["id"], e)
            item["card_blob"] = ""
        p[track].append(item)
        have.add(item["id"])
        added += 1
        # persist as we go so a timeout never loses work
        allp = _load(store, POOL_BLOB, {})
        allp[track] = p[track]
        _save(store, POOL_BLOB, allp)
        _save(store, STATE_BLOB, state)
    notes.append(f"{track}: pool {len(p[track])}/{n} (+{added}, {time.time() - t0:.0f}s)")
    return notes


def ensure_all(store, budget_s=540):
    notes = []
    t0 = time.time()
    for t in TRACKS:
        left = budget_s - (time.time() - t0)
        if left < 20:
            notes.append("budget exhausted")
            break
        notes += ensure_pool(store, t, budget_s=min(left, 200))
    return notes


def reset_pool(store):
    _save(store, POOL_BLOB, {})
    return ["edu pool cleared — regenerating on the next timer / on demand"]


# ---------- caption ----------

def caption(item):
    t = item["track"]
    lines = [item["hook"], "", f"\U0001F9E9 {item['question']}"]
    if item.get("options"):
        lines.append("")
        lines += [f"  {o}" for o in item["options"]]
    lines += ["", "\U0001F4AC Comment your answer BEFORE you expand this post.", "",
              "─── Answer ───", "", item["answer"]]
    if item.get("code"):
        lines += ["", "\U0001F40D Code:", item["code"]]
    if item.get("complexity"):
        lines += ["", f"⏱ {item['complexity']}"]
    if item.get("takeaway"):
        lines += ["", f"\U0001F511 Takeaway: {item['takeaway']}"]
    if t == "papers" and item.get("url"):
        lines += ["", f"\U0001F4C4 Paper: {item['url']}"]
    lines += ["", FOLLOW_CTA, "♻️ Repost to help someone prepping this week.", "",
              TRACK_TAGS[t] + "".join(f" #{x}" for x in item.get("tags", []) if x)]
    cap = "\n".join(lines)
    if len(cap) > 2900:
        cap = cap[:2860].rsplit("\n", 1)[0] + "\n\n" + TRACK_TAGS[t]
    return cap


# ---------- posting ----------

def post_one(store, track):
    """Post the next item for `track`: pool → generate on the fly → seed bank.
    Returns notes; '1 posted, …' on success (never raises)."""
    import linkedin_client
    p = pool(store)
    state = _load(store, STATE_BLOB, {"used": [], "papers_seen": []})
    item = None
    src = "pool"
    if p[track]:
        item = p[track].pop(0)
        allp = _load(store, POOL_BLOB, {})
        allp[track] = p[track]
        _save(store, POOL_BLOB, allp)
    else:
        src = "on-the-fly"
        try:
            sec = _cfg(store)
            paper = None
            if track == "papers":
                cands = _paper_candidates(store, state)
                paper = cands[0] if cands else None
                if paper:
                    state.setdefault("papers_seen", []).append(paper["url"])
            item = generate_one(store, track, sec, state, paper) if (track != "papers" or paper) else None
        except Exception as e:
            log.info("on-the-fly generation failed: %s", e)
            item = None
        if item is None:
            src = "seed"
            used = {u.get("id") for u in state.get("used", [])}
            fresh = [s for s in seed_items(track) if s["id"] not in used]
            if not fresh:
                return [f"edu {track}: nothing available (pool empty, LLM down, seeds used)"]
            item = fresh[0]
        item["number"] = _next_number(state, track)
        try:
            _render_and_store(store, item)
        except Exception as e:
            log.warning("render failed: %s", e)
            item["card_blob"] = ""
    png = None
    if item.get("card_blob"):
        try:
            png = store.download_blob(item["card_blob"]).readall()
        except Exception:
            png = None
    if png is None:
        try:
            import edu_cards
            png = edu_cards.render(track, item["question"], item.get("visual"), item.get("number"), item.get("difficulty"))
        except Exception:
            png = None
    text = caption(item)
    title = f"{TRACK_NAMES[track]}: {item['hook'][:80]}"
    note = ""
    try:
        if png:
            urn = linkedin_client.post_with_image(text, png, title=title)
        else:
            urn = linkedin_client.post_text(text)
    except Exception as e:
        try:
            urn = linkedin_client.post_text(text)
            note = f" (text-only after: {str(e)[:80]})"
        except Exception as e2:
            # put it back so the content isn't lost
            if src == "pool":
                allp = _load(store, POOL_BLOB, {})
                allp[track] = [item] + list(allp.get(track, []))
                _save(store, POOL_BLOB, allp)
            return [f"edu {track} failed: {str(e)[:100]} | text: {str(e2)[:80]}"]
    state.setdefault("used", []).append({"id": item["id"], "track": track, "q": item["question"][:90],
                                         "ts": _now().isoformat(), "urn": urn})
    state["used"] = state["used"][-600:]
    _save(store, STATE_BLOB, state)
    try:
        plog = _load(store, "li_post_log.json", [])
        plog.append({"ts": _now().isoformat(), "company": "edu", "variant": track, "urn": urn,
                     "title": item["hook"][:120], "source": src})
        _save(store, "li_post_log.json", plog[-2000:])
    except Exception:
        pass
    return [f"posted edu {track} #{item.get('number')} ({src}): {item['hook'][:60]} {urn}{note}",
            f"1 posted, {len(pool(store)[track])} {track} left"]


# ---------- digests for the daily email ----------

def plan_text(store):
    """Today's queued questions per track (for the morning email)."""
    p = pool(store)
    tg = targets(store)
    lines = []
    for t in TRACKS:
        items = p[t]
        lines.append(f"{TRACK_NAMES[t]} ({len(items)} ready of {tg[t]} planned):")
        for it in items[:tg[t]]:
            lines.append(f"  • {it['hook']}")
        if not items:
            lines.append("  (generated on the fly at post time)")
    return "\n".join(lines)


def posted_text(store, hours=24):
    """What went out in the last `hours`, grouped, with links."""
    plog = _load(store, "li_post_log.json", [])
    cutoff = (_now() - timedelta(hours=hours)).isoformat()
    recent = [p for p in plog if p.get("ts", "") >= cutoff]
    by = {}
    for p in recent:
        by.setdefault(p.get("variant"), []).append(p)
    jobs = sum(len(v) for k, v in by.items() if k and k.endswith("_hook"))
    lines = [f"Posted in the last {hours}h: {len(recent)} total — {jobs} job cards, "
             + ", ".join(f"{len(by.get(t, []))} {TRACK_NAMES[t]}" for t in TRACKS)
             + f", {len(by.get('poll', []))} poll, {len(by.get('carousel', []))} carousels, "
             f"{sum(len(by.get(k, [])) for k in ('news', 'hn', 'paper', 'chart'))} news/charts"]
    for t in TRACKS:
        for p in by.get(t, [])[:10]:
            urn = p.get("urn") or ""
            link = f"https://www.linkedin.com/feed/update/{urn}/" if urn.startswith("urn:") else ""
            lines.append(f"  [{TRACK_NAMES[t]}] {p.get('title', '')[:70]}  {link}")
    return "\n".join(lines)
